services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=book_library
      - DB_PASSWORD=Amit@8085
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Amit@8085
      POSTGRES_DB: book_library
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: